apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-django
  template:
    metadata:
      labels:
        app: blog-django
    spec:
      containers:
      - name: blog-django
        image: 277707108897.dkr.ecr.us-east-2.amazonaws.com/django-app-2:01
        envFrom:
        - secretRef:
            name: mongo-secret
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: blog-django-service
spec:
  type: LoadBalancer
  selector:
    app: blog-django
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
